dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T cmake-0.0.1-Linux.deb  -ushebdim:$BINTRAY_API_KEY "https://api.bintray.com/content/yaotkrit/cpplearn/helloworld/1/cmake-0.0.1-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
 
